### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by cbrnr**
Work in progress. Here's what I did and what we should consider adopting as the default code style:

- Lines must not exceed 79 characters.
- Use instance attributes instead of class attributes.
- Functions and variables should be lower case separated by underscores.

For me, the major challenge is to keep everything within 79 characters per line.

### CODE REVIEW

**Comment by cbrnr** [comment]
I have a question: the `dataThread` class has an attribute `self.streamMetadata = {}` (an empty dict initially), but in `updateStreams` you access this as

```
for k in range(len(self.streams)):
    self.streamMetadata[k] = {
        "streamName": self.streams[k].name(),
        "channelCount": self.streams[k].channel_count(),
        "channelFormat": self.streams[k].channel_format(),
        "nominalSrate":self.streams[k].nominal_srate()
    }
```

using `self.streamMetadata[k]` as a list index. In addition, this does not seem to properly initialize the list, but it does work as a dict - but this seems pretty hacky if you ask me. If you really want a sorted list of metadata per stream (sorted by stream number), then I'd recommend to really use a list.

**Comment by cbrnr** [comment]
The remaining part of `paintwidget.py` is hard to refactor without being able to receive signals. Could you look into why the little toy example does not work?

```
import time
from random import random as rand
from pylsl import StreamInfo, StreamOutlet

info = StreamInfo('BioSemi', 'EEG', 8, 100, 'float32', 'myuid34234')
outlet = StreamOutlet(info)

print("now sending data...")
while True:
    mysample = [rand(), rand(), rand(), rand(), rand(), rand(), rand(), rand()]
    outlet.push_sample(mysample)
    time.sleep(0.01)
```

**Comment by cbrnr** [comment]
If you want, you could test if everything works on your machine with the changes in this PR. If yes, you could merge it and we'll take care of `paintwidget.py` in another PR (but please see my two questions above).

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens, thanks so much for contributing!

Yes I originally made `self.streamMetadata` a dictionary but later decided to make it a list instead, and I forgot to update it in the initialization. I will fix it.

Your sender script works from my side though: what errors did you get? I developed the scripts in Visual Studio Code, Python 3.7 64 bit.

**Comment by cbrnr** [comment]
I'm getting this error when trying to receive the data from the sender script:

```
Traceback (most recent call last):
  File "/Users/clemens/Repositories/SigVisualizer/paintwidget.py", line 43, in run
    chunk, timestamps = self.inlet.pull_chunk(max_samples=self.chunkSize)
  File "/Users/clemens/anaconda/lib/python3.6/site-packages/pylsl/pylsl.py", line 844, in pull_chunk
    handle_error(errcode)
  File "/Users/clemens/anaconda/lib/python3.6/site-packages/pylsl/pylsl.py", line 1134, in handle_error
    raise InternalError("an internal error has occurred.")
pylsl.pylsl.InternalError: an internal error has occurred.
```

I guess I will need to debug into `pylsl` to find out. I'm trying this on a Mac, and I get the error with both Python 3.6 and 3.7.

**Comment by cbrnr** [comment]
Also, receiving the data with the simple receiver script works just fine, so it's got to be a problem on our side...

**Comment by Yida-Lin** [comment]
That's weird... I will look into it tonight

**Comment by cbrnr** [comment]
It doesn't work on Linux either, I get the same error message.

**Comment by cbrnr** [comment]
Maybe it has something to do with the fact that the LSL stuff is running in a QThread?

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens, hmm quite difficult to tell from here...

Btw I just discovered that there is already an existing [visualizer](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Python/examples/ReceiveAndPlot.py) from official LSL github website; it's a minimal script so it doesn't take care of scaling etc. but seems it works pretty well.

Not sure whether we should abort our project, or keep it, or adapt to the style of this existing script?

(I like in this script how the signals continuously moving towards left, while [mine](https://www.youtube.com/watch?v=ntvWea8uE2g&feature=youtu.be) currently is page based, from left to right and then start over)

**Comment by Yida-Lin** [comment]
@cbrnr Just realized the existing script couldn't pull the 10kHz signals fast enough so I guess we still have a valid reason to develop our own.

But I would like to hear your opinion on the sliding window approach vs. page based approach.

**Comment by cbrnr** [comment]
Or can we make this work without pushing the data collection into a separate thread? I saw that in their example they are using a non-blocking call with a timeout of 0, so maybe this works in the main thread?

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens!

Great that you found out the reason! The problem doesn't sound ideal though, it means almost certain that we might have to abandon Python and move back to C++.

I know it's quite difficult for you to judge without actually seeing the 2 applications, so I made the following videos:

1. [pylsl vis tool](https://youtu.be/2Oqgv1yuIBI) on synthetic data
2. [pylsl vis tool](https://youtu.be/IsZykpId5CU) on real data (10kHz, doesn't scale well, also too slow)
3. [Current version of our solution](https://youtu.be/r7zYAAhw_ic) on the same file above

Not sure whether I am wrong, but I think it would be very difficult if it cannot be executed in a second thread, as we have to leave the main thread to the Qt GUI, right? Although I know it's not un-doable (actually my first sketch you first saw in an email was single threaded), but it's not an orthodox approach for a GUI app.

About the sliding window vs. page-based approach, I think the the sliding window is more beautiful, but it might be very slow as it needs to plot everything again every frame, right? As in page-based approach, I plot a tall and narrow rectangle every time, that's why it can plot fast enough high freq signals. But I am open on this topic

**Comment by cbrnr** [comment]
Thanks for sharing these videos! Something seems to be wrong with the pylsl tool on the 10kHz data, because it just keeps squeezing the x axis instead of scrolling. Our solution looks really nice though! The page-based approach is much better than the continuous approach. The user needs to spot tiny waves in the ongoing EEG, and this is much easier if the signals don't move continuously. Almost all proprietary solutions use such a page-based approach, so I think we should keep our main focus on this mode.

Regarding Python vs. C++, let's not decide this right now. Going back to C++ means that signal processing will be much more cumbersome. Also, development time will also be increased as compared to Python. But of course if we find that it is impossible to implement our app in Python we will have to switch.

I suggest we pursue either (or both) of the following two things:

1. Find out what the problem with running LSL in a second thread on Unix is. Maybe this issue can be solved and we're good to go.
2. Try to fetch the data in the main thread. This should be possible by setting the timeout to 0 when pulling chunks. This is also how it is done in the pylsl vis tool, and I assume that LSL is running in a separate thread anyway. We just need to make sure we don't block our GUI, and we can do this with the timeout argument.

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens!

Great! Saw your thread on the LSL repo. As I understand, this problem is already solved in the newer version of pylsl, and so long as they update PYPI also, then we are good, is that correct?

I would prefer python also as I have relatively less experience with it and would love to keep practicing a bit.

**Comment by cbrnr** [comment]
Exactly! I already tried the newest version and it works! As soon as this version is available on PyPI we're good to go!

**Pull request merged**
