### PR TITLE
Visualize markers overlaid on signals

### PR DESCRIPTION
**Pull request by cboulay**
The first 3 commits are part of #12 

The last commit changes quite a bit of code, but it enables visualizing markers overlaid on top of signals. The only way to do this without blanking out the entire region under the marker is to update both signals and markers in the same painter update. This required a bit of restructuring.

### CODE REVIEW

**Comment by Yida-Lin** [comment]
Thanks @cboulay , that's a great idea. Currently with the last commit after clicking "update streams" button it no longer pulls the signals though; not sure what went wrong

**Comment by cboulay** [comment]
Hmm. It was working when I left the lab 5 minutes ago. What is your test setup?

**Comment by Yida-Lin** [comment]
@cboulay I used [XDF Streamer](https://github.com/Yida-Lin/XDFStreamer) to generate some random signals and push to LSL. The same setup worked with #12

**Comment by cboulay** [comment]
I’ll try that tonight.

**Comment by cboulay** [comment]
Sorry about that. I hadn't tested when no marker stream was present. This latest commit should do the trick.

**Comment by Yida-Lin** [comment]
@cboulay It works great now, thanks Chadwick!

**Pull request merged**
